config/routes.rb
Rails.application.routes.draw do

  root 'chatrooms#index'

  get 'signup' => 'users#new', as: :sign_up

  post 'users' => 'users#create'

  get '/signin' => 'sessions#new', as: :sign_in

  post '/signin' => 'sessions#create'

 delete 'sign_out' => 'sessions#destroy', as: :sign_out

  get 'chatrooms/:id' => 'chatrooms#show', as: :chatroom

 namespace :api do
    get "chatrooms/:id" => 'chatrooms#show'
    post "chatrooms/:id/messages" => 'messages#create', as: :messages
  end

end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :chatroom
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :messages  



end

app/controllers/api/chatrooms_controller.rb
class Api::ChatroomsController < ApplicationController

  def show
   @chatroom = Chatroom.find params[:id]
  end
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController

  before_action :logged_in_user

  def create
   @message = Message.new params.require(:message).permit(:content)
   @message.chatroom = Chatroom.find (params[:id])

   @message.user = @current_user
   if @message.save
     render status: 201, json: @message
   else
     render status: 422, json: @message.errors
   end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:danger]= "Please Log In"
      redirect_to log_in
    end
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController


  def new
  end

  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatrooms = Chatroom.all
    @chatroom = Chatroom.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
      user = User.find_by_email(params[:email])

      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: "Welcome back"
      else
        render :new
      end
  end

    def destroy
      session[:user_id] = nil
      redirect_to sign_in_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
 end

 def create
   @user = User.new(user_params)
   if @user.save
     log_in @user
   redirect_to root_path, notice: "Welcome to Image App"
  else
    render:new

   end
 end

 def user_params
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
 end
end

app/helpers/api/chatrooms_helper.rb
module Api::ChatroomsHelper
end

app/helpers/api/messages_helper.rb
module Api::MessagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
      session[:user_id] = user.id
    end

    def current_user
      @current_user = User.find_by(id: session[:user_id])
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end

    def logged_in?
      !current_user.blank?

    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/index.html.erb
<div class="pull left">
  <div class="sidebar">
    <% if logged_in? %>
    <ul>
    <% @chatrooms.each do |room| %>
      <li><%= link_to room.name.upcase, chatroom_path(id: room.id)%></li>
    <% end %>

  </ul>
  <% end %>
  </div>
</div>
<% if logged_in? %>
<h1>Please select a room to view</h1>
<% else %>

<div class="center jumbotron">
    <h2>Welcome to SLAcKk</h2>

    <%= link_to "Sign up now!", sign_up_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/chatrooms/show.html.erb
<div class= "messagechats">
<%= react_component "ChatRoom", {id:@chatroom.id} %>
</div>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top">
  <div class = "container">
    <div class = "navbar-brand">
      <%= link_to "SLAcKk", root_path %></div>
    <nav>
      <ul class = "nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
          <% if logged_in? %>
           <li><%= link_to 'Log Out', sign_out_path, method: :delete %><li>
      </ul>
       <% else %>
         <li><%= link_to "Log In", sign_in_path %>
         </nav>
       <% end %>
       </ul>
   </header>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uslack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>
  <div class ="header-style">
   <%= render 'layouts/header' %>
 </div>
  <%= yield %>
</body>
</html>

app/views/users/new.html.erb
<%= simple_form_for @user do |u| %>
  <%= u.input :first_name %>
  <%= u.input :last_name  %>
  <%= u.input :email %>
  <%= u.input :password %>
  <%= u.input :password_confirmation, label: "Password Confirmation" %>
  <%= u.submit "Sign Up", class: "btn btn-primary btn-block btn-lg" %>
<% end %>